excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - storelink-iosTests
  - storelink-iosUITests
  
type_body_length:
  - 300 # warning
  - 400 # error
