excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - StorelinkTests
  - StorelinkUITests
  
type_body_length:
  - 300 # warning
  - 400 # error
  
whitelist_rules:
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - trailing_comma
  - empty_enum_arguments
  - fatal_error_message
  - force_cast
  - force_try
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - control_statement
  - cyclomatic_complexity
  - duplicate_imports
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - function_parameter_count
  - generic_type_name
  - leading_whitespace
  - mark
  - opening_brace
  - statement_position
  - trailing_semicolon
  - unneeded_break_in_switch
  # - empty_count
  # - for_where
  # - identifier_name
  # - line_length
  # - multiple_closures_with_trailing_closure
  # - nesting
  # - redundant_discardable_let
  # - syntactic_sugar
  # - vertical_parameter_alignment
  # - yoda_condition
